name: ICS 199
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
timezone: Pacific/Honolulu # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
baseurl: /morea
exclude: [morea]
morea_theme: cerulean-purple
morea_navbar_items:
  - Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

logger_factory:
  # Possible Morea logger values:
  #  error (fatal errors only. combine with -q on command line for least amount of output). The default.
  #  warn  (error + missing optional YAML matter.)
  #  info  (error + warn + summary of processing steps)
  #` debug (all of the above plus internal state information, for developers only)
  Morea: error

# The following properties are optional.
# See the User Guide (http://morea-framework.github.io/userguide.html) for more info.

# morea_course: ics311
# morea_domain: http://morea-framework.github.io/
# morea_google_analytics_tracking_id: "<your tracking id here>"

#morea_head_breadcrumb_link: "http://cnn.com"
#morea_head_breadcrumb_label: "CNN Site"
